apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app  : ftps
    owner: elaronda
spec:
  selector:
    matchLabels:
       app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        app  : ftps
        owner: elaronda
    spec:
      containers: 
      - name           : ftps
        image          : ftps-image
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 14888
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  labels:
    app  : ftps-svc
    owner: elaronda
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  selector:
    app: ftps
  ports:
    - name      : port20
      protocol  : TCP
      port      : 20
      targetPort: 20
    - name      : port21
      protocol  : TCP
      port      : 21
      targetPort: 21
    - name      : portdef
      protocol  : TCP
      port      : 14888
      targetPort: 14888