apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app  : mysql-svc
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - name      : port-mysql
    protocol  : TCP
    port      : 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app  : mysql
spec:
  selector:
    matchLabels:
       app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        app  : mysql
    spec:
      containers:
      - name           : mysql
        image          : mysql-image
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        volumeMounts:
          - name     : mysql-volume
            mountPath: "/var/lib/mysql"
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pv-claim