apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app  : phpmyadmin
    owner: elaronda
spec:
  selector:
    matchLabels:
       app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
        owner: elaronda
    spec:
      containers:
      - image: phpmyadmin-image
        name: phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  labels:
    app: phpmyadmin-svc
    owner: elaronda
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  ports:
    - protocol: TCP
      name: wp
      port: 5000
      targetPort: 5000
  selector:
    app: phpmyadmin